### ISSUE TITLE
Compilation error: data-layout differs

### ISSUE THREAD

**Issue by Bromind** [kent-weak-memory/rust#3]
Hi, 

I'm trying to compile the compiler. When running `python3 x.py build`, I run into an error when building stage 1 std artifacts: 
```
error: internal compiler error: compiler/rustc_codegen_llvm/src/context.rs:176:13: data-layout for target `aarch64-unknown-freebsd-purecap`, `e-m:e-pf200:128:128:128:64-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128-A200-P200-G200`, differs from LLVM target's `aarch64-unknown-freebsd` default layout, `e-m:e-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128`
```

By any chance, did you already encountered this error?

(If need be, I can upload the full log and/or the config.toml)

(This error may also come from my (cheribuild built) LLVM, but since I encountered this error while trying to compile Rust, it could be useful to have a note about it here for future reference.)

**Comment by graymalkin** [comment]
It looks like `x.py` is hooked up to a non-CHERI LLVM through your `config.toml`. Can you share your config? Mine looks like this:

```toml
# Includes one of the default files in src/bootstrap/defaults
profile = "codegen"
changelog-seen = 2

[build]
# "aarch64-apple-darwin", 
target = ["aarch64-apple-darwin", "aarch64-unknown-freebsd", "aarch64-unknown-freebsd-purecap"]
docs = false

[install]
prefix = "./build/install-stage2-latest"
sysconfdir = "./build/install-stage2-latest"
# TODO: check if this is okay: docs = false

# Replace with whatever architecture you're building and running the compiler from.
[target.aarch64-apple-darwin]
# Use Morello build of LLVM, this seems to control what the compiler is linked with.
# The Morello fork seems to support all the normal architectures, plus Morello-specific options.
# We need the Morello-specific options so that we can cross compile.
# You'll need a Morello SDK build: `cheribuild.py cheribsd-morello-purecap`
llvm-config = "/Users/simon/cheri/output/morello-sdk/bin/llvm-config"

[target.x86_64-unknown-linux-gnu]
llvm-config = "/Users/simon/cheri/output/morello-sdk/bin/llvm-config"


[target.aarch64-unknown-freebsd]
# This doesn't appear to do anything, presumably only the one for the host has any effect?
# llvm-config = "/Users/simon/cheri/output/morello-sdk/bin/llvm-config"
# These wrappers force clang to use the right target and system libraries.
# Without it, the build system appears to default to host libc/libm/etc, which are the wrong arch.
# It'd be cleaner just to pass the extra flags, but I haven't found an option for that.
#
# Note that this requires having a FreeBSD build, which you can get like this:
# `cheribuild.py freebsd-aarch64`
#
# The path here is just a path, change it to match your home and cheribuild paths.
# The scripts will also need updating to match your home and cherbuild paths.
cc = "/Users/simon/github/rust/clang-freebsd.sh"
cxx = "/Users/simon/github/rust/clang++-freebsd.sh"
linker = "/Users/simon/github/rust/clang-freebsd.sh"
# Use Morello SDK's binutils for compilation.
# The host's binutils might be fine here, but may as well use the Morello tools for consistency.
# Leaving these options out entirely seems to confuse the build system somehow.
ar = "/Users/simon/cheri/output/morello-sdk/bin/ar"
ranlib = "/Users/simon/cheri/output/morello-sdk/bin/ranlib"

[target.aarch64-unknown-freebsd-purecap]
# This doesn't appear to do anything, presumably only the one for the host has any effect?
# llvm-config = "/Users/simon/cheri/output/morello-sdk/bin/llvm-config"
# Options needed for building the standard library, as and when that's supported.
cc = "/Users/simon/github/rust/clang-morello.sh"
cxx = "/Users/simon/github/rust/clang++-morello.sh"
ar = "/Users/simon/cheri/output/morello-sdk/bin/ar"
ranlib = "/Users/simon/cheri/output/morello-sdk/bin/ranlib"
linker = "/Users/simon/github/rust/clang-morello.sh"

# You can compile programs with the above targets like this:
# `build/aarch64-apple-darwin/stage1/bin/rustc --out-dir /tmp/build --target aarch64-unknown-freebsd -C linker=/home/rust-20211014/clang-freebsd.sh test.rs`
# Output appears in /tmp/build, which helps avoid splurging intermediate files about accidentally.
```


If you're on aarch64 macOS you can also grab a pre-built distribution from the releases page on this repo.
